Desafio1
bruno-br/onboarding_environment pull request #1
Opened 2021-12-02 14:28 UTC by bruno-br

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/Gemfile
> +gem 'sass-rails', '~> 4.0.0'
É bom remover as gemas que não são usadas no projeto

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
> +    # Check if any params are missing
Não precisa de comentários que podem ser inferidos pelo código

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
> +    product = Product.find_by(id: params[:id])
Tratar com 404 produtos não encontrados

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/app/assets/javascripts/application.js
> +// This is a manifest file that'll be compiled into application.js, which will include all the files
Remover esses assets que não são usados

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
> +      render json: { message: 'Product not found', data: nil }, status: :error
Retornar 404

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
> +    return render json: { message: 'Product not found' }, status: :error if product.nil?
Retornar 404

2021-12-02 14:59 UTC, ArthurFreitas commented on rails/app/myapp/test/fixtures/products.yml
> +one:
As fixtures são usadas em testes, nesse desafio não precisa. Mas, pode manter.

2021-12-02 15:14 UTC, NoahCamargo requested changes

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/config/routes.rb
> +  patch 'products' => 'products#update'
Aqui poderia ser usado o `resources` que resumiria as rodas do CRUD

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/README.rdoc
> +<tt>rake doc:app</tt>.
Adicione o readme para a API

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/models/product.rb
> +  field :SKU, type: String
Acredito que seria bom manter o padrão em tudo minusculo

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +    end
Acredito que essa parte de verificação de parâmetros faltando, possa ser resumida adicionando um `validate` de presença no modelo https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validates_presence_of

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +    end
Pode ocultar a mensagem, pois o status code já me informa qual a situação

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +      render json: { message: 'Created', data: product }, status: :created
Não é muito interessante jogar o direto o modelo para a renderização pois assim todos os campos são retornados e isso pode vir a ser uma vulnerabilidade, alem de retornar foda do padrão da api e impactar na performance.

```
"_id": {
            "$oid": "61a8dfc97027bb009314f419"
        },
``` 

Faça com que isso seja resumido em `"id": "61a8dfc97027bb009314f419"`

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +      render json: { error: true, message: 'Failed' }, status: :error
Tende deixar a api mais com o conceito de RESTFUL. Aqui no caso, quando o erro acontece esta retornando 500, o que não é legal, nesse caso é mais interessante um 400

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +    render json: { data: product }
Esse data ficou um pouco genérico demais, no caso do show, poderia retornar só o objeto ou "product"

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +    render json: { data: products }
Nesse caso, poderia ser "products"

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/config/routes.rb
> +  patch 'products' => 'products#update'
Nesse caso, como pode ser atualizado o objeto inteiro, fica melhor um put (também é o mais comum de ver)

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/config/routes.rb
> +  patch 'products' => 'products#update'
Tambem faltou o :id

2021-12-02 15:14 UTC, NoahCamargo commented on rails/app/myapp/config/routes.rb
> +  #   end
Remova os comentários

2021-12-02 21:11 UTC, ArthurFreitas commented on rails/README.md
> +      }
Aqui sobrou }

2021-12-02 21:11 UTC, ArthurFreitas commented on rails/README.md
> +    Informar no Body as propriedades que serao alteradas
O comportamento de realizar update parcial é do PATCH e não do PUT.

2021-12-02 21:17 UTC, NoahCamargo requested changes

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +                          name: params[:name], price: params[:price])
Para criação e atualização no rails, voce pode usar com o conceito de permitted_params, onde voce filtra no params só os campos que quer e passa para o new.

```
def permitted_params
  params.permit(:sku, :amount)
end

def create
  product = Product.new(permitted_params)
```

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +      render json: { message: 'Created', product: product }, status: :created
Pode tirar o `message` para todos

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +      is_success = product.update_attribute(param[:name], param[:value])
O `update_attribute` gera uma `query` no banco de dados, o que deixa a requisição mais lenta e em grandes quantidades pode impactar o banco. Nesse caso, o update esta dentro de um loop fazendo campo por campo, o que não é interessante.

Faça um update de uma vez no modelo passando os valores, caso um erro acontece, ele poderá ser resgatado chamando `errors`, do modelo

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +  end
Com a nova abordagem sugerida, esse cara será desnecessário

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/models/product.rb
> +  validates :sku, presence: true
Adicione um enter entre os fileds e o validates, faça tambem entre o include e os fields

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/app/models/product.rb
> +    h['id'] = id.to_s
Aqui da pra fazer tudo em uma linha, mas isso seria só questão de gosto mesmo

```
  def as_json(*_args)
    h = super()
    h['id'] = h.delete('_id').to_s
    h.as_json(only: %w[id sku name description amount price])
  end
```

2021-12-02 21:17 UTC, NoahCamargo commented on rails/app/myapp/config/routes.rb
> +  resources :products, only: %i[index show create update destroy]
É possível adicionar utilizar o `except`, e colocar apenas o que você não quer

```
resources :products, except: %i[new edit]
```

2021-12-03 17:36 UTC, ArthurFreitas approved these changes
Parabéns

2021-12-03 17:36 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
>        render json: {}, status: :bad_request
Aqui poderia retornar uma resposta vazia no lugar de json vazio

2021-12-03 17:36 UTC, ArthurFreitas commented on rails/app/myapp/app/models/product.rb
> +# Product Model
Comentário desnecessário

2021-12-03 17:36 UTC, ArthurFreitas commented on rails/app/myapp/app/controllers/products_controller.rb
> +    render json: { error: true }, status: :error
Num caso real os erros seriam melhor especificados

2021-12-03 17:37 UTC, NoahCamargo approved these changes

2021-12-03 17:37 UTC, NoahCamargo commented on rails/app/myapp/app/controllers/products_controller.rb
> +      render json: {}, status: :bad_request
No caso de falhar, poderia retornar os erros presentes em product.errors

2021-12-03 17:44 UTC, merged