Desafio 2
bruno-br/onboarding_environment pull request #2
Opened 2021-12-08 18:19 UTC by bruno-br

2021-12-08 20:31 UTC, NoahCamargo requested changes

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +
Remover este espaço

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    with {:ok, %Product{} = product} <- Management.create_product(product_params) do
Durante os PRs para produção, o pessoal costuma pedir para não usar with com uma condição, nesses casos substituir por case. Mas eu pessoalmente gosto assim, mas evito para o PR subir de primeira kk

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +      send_resp(conn, :not_found, "")
Para não ficar carregando o produto a cada action e verificar o not_fount, voce poderia criar um `plug`, que tem o mesmo funcionamento do `before_action` no rails

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    end
Elixir não tem `return` e chamar o `send_resp` não vai fazer com que a execução pare aqui. Nesse caso ele vai tentar passar product com o valor de nil para a `update_product` e quebrar.
Se olhar no console do servidor vai ser possível ver o erro

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    end
Mesmo caso do update

2021-12-08 20:31 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    end
Retorne 204 ao sucesso com uma resposta vazia

2021-12-09 21:41 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    with {:ok, %Product{} = product} <- Management.create_product(product_params) do
O credo reclama do with com uma condição só

2021-12-09 22:40 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/router.ex
> +    resources "/products", ProductController, except: [:new, :edit]
A rota precisa ser igual ao do desafio 1.

2021-12-09 22:40 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +    if product == nil do
com o with tu poderia fazer algo assim:

```
with {:ok, product} <- Management.get_product(id),
         {:ok, %Product{} = product} <- Management.update_product(product, product_params) do
      render(conn, "show.json", product: product)
    else
      {:error, :not_found} -> send_resp(conn, :not_found, "")
      {:error, %Ecto.Changeset{} = changeset} -> #render errors
      error -> #unknown error
    end
```

2021-12-10 15:07 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +      _ ->
Aqui tu poderia só retornar o error, que iria cair no FallbackController

2021-12-10 15:17 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/plugs/product_plug.ex
> +    with true <- conn.params["id"] != nil,
Aqui poderia resultar em 400 no lugar de 404, já que o problema é que a requisição está mal formada.

2021-12-10 15:17 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +         {:ok, %Product{} = updated_product} <- Management.update_product(product, product_params) do
Se o update falhar deveria retornar 422, dá uma olhada no fallbackcontroller linha 10.

2021-12-10 15:17 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +         {:ok, %Product{}} <- Management.delete_product(product) do
422 aqui também

2021-12-10 15:17 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +  def show(conn, %{"id" => id}) do
Ta correto

2021-12-13 12:24 UTC, NoahCamargo approved these changes

2021-12-13 12:24 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/plugs/product_plug.ex
> +  def get_product(conn, _opt), do: find_by_id(conn, conn.params["id"])
Ficou bom com o Plug, porem, o mais correto seria passar o Plug como parâmetro para `plug` e definir as funções de `init` e `call`

2021-12-13 12:24 UTC, ArthurFreitas approved these changes

2021-12-13 13:12 UTC, merged