Desafio 4
bruno-br/onboarding_environment pull request #4
Opened 2021-12-23 14:43 UTC by bruno-br

2021-12-23 17:00 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/cache/redis_api_test.exs
> +      client = RedisApi.start()
Teus testes unitários precisam rodar sem chamar serviços externos (ElasticSearch, Redis, etc.). Para isso tu precisa usar uma técnica chamada Mock que simula o comportamento desses serviços nos testes.

Dá uma lida em:
https://stuart.com/blog/tech/mocks-safely-elixir-tests/

2021-12-23 17:00 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/cache/redis_api_test.exs
> +      client = RedisApi.start()
A maioria dos nossos testes de produção é síncrono (e lentos) pois usam a lib https://github.com/jjh42/mock ,apesar de o link que mandei dar uma solução melhor tu pode usar qualquer uma delas para esse exercício.

2021-12-23 17:00 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/cache/redis_api_test.exs
> +      client = RedisApi.start()
Nesses casos o teu teste se resume a checar se a chamada a lib externa query/2 recebeu os argumentos corretos (valor encodado, etc).

2021-12-23 17:09 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/cache/redis_api_test.exs
> +  @set_params %{
Uma opção mais limpa para setar valores uma única vez para todos os testes é usar o callback setup_all. https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html


```
setup_all do
  [ key: "value" ]
end

test "when using setup_all", %{
  key: value
} do
  assert value == "value"
end
```

2021-12-23 17:18 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +  use Myapp.DataCase
Como está usando ativamente o DB nos testes precisa setar o async para false

2021-12-23 17:19 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +  def product_fixture(attrs \\ %{}) do
Função auxiliar deve ser privada e mantida no fim do arquivo

2021-12-23 17:19 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +  @valid_attrs %{
setup_all aqui também

2021-12-23 17:20 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +    test "returns the product with given id" do
Precisa testar se o id não existe no banco.

2021-12-23 17:22 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +  describe "get_product!/1" do
A convenção é só usar "!" no fim de uma função, se ela levantar exceções https://hexdocs.pm/elixir/main/naming-conventions.html#trailing-bang-foo. Nesse caso pode remover

2021-12-23 17:25 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +    test "returns error when data is invalid" do
Falta verificar a mensagem do erro em todos esses casos

2021-12-23 17:26 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +  @valid_attrs %{
setup_all aqui

2021-12-23 17:27 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +  def fixture(:product) do
Essa função deve ser privada e ficar lá no fim do arquivo

2021-12-23 17:27 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert length(json_response(conn, 200)["products"]) == length(list_products())
Verifica se o conteúdo da resposta está correto também

2021-12-23 17:28 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert %{
Extrai para uma variável "expected_response", fica mais facil de ler.

2021-12-23 17:29 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      conn = get(conn, Routes.product_path(conn, :show, id))
No lugar de fazer outro request melhor só fazer uma query diretamente no banco.

2021-12-23 17:29 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert %{"id" => id} = json_response(conn, 201)["product"]
Sempre separa a ação sendo testada dos asserts.

2021-12-23 17:30 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert json_response(conn, 422)["errors"] != %{}
Dá assert no conteúdo da resposta também.

2021-12-23 17:32 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/management_test.exs
> +  def product_fixture(attrs \\ %{}) do
Ou melhor, faz que nem o product_controller_test com setup [:create_product]

2021-12-23 17:33 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert %{
Extrai o expected para uma var

2021-12-23 17:34 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert json_response(conn, 422)["errors"] != %{}
Verificar mensagem explicando os erros

2021-12-23 17:34 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert response(conn, 204)
Verificar se o produto existe no banco

2021-12-23 17:34 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +defmodule MyappWeb.ProductControllerTest do
async para false quando usa o DB

2021-12-23 17:35 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/plugs/get_product_plug_test.exs
> +  describe "get product" do
Aqui tu precisa testar o GetProductPlug.call/1 diretamente

2021-12-23 17:37 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp_web/plugs/get_product_plug_test.exs
> +    ManagementTest.product_fixture()
Extrai para um helper, ou o DataCase para reduzir acoplamento entre arquivos de teste diferentes

2021-12-28 16:59 UTC, phrodrigues commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +  describe "index" do
Seria interessante testar o efeito do plugin de log do els na controller

2022-01-05 12:22 UTC, phrodrigues commented on phoenix/app/myapp/lib/myapp/services/elasticsearch_service.ex
> +    |> get_path_with_index
https://github.com/christopheradams/elixir_style_guide#parentheses-pipe-operator

2022-01-05 12:22 UTC, phrodrigues commented on phoenix/app/myapp/lib/myapp/services/elasticsearch_service.ex
> +  def list(path, limit) do
Faria sentido usar o |> nesse método

2022-01-05 12:22 UTC, phrodrigues commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert_called(
Seria melhor juntar todas essas asserções do els num único método

2022-01-05 14:38 UTC, NoahCamargo requested changes

2022-01-05 14:38 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/management.ex
>    alias Myapp.Management.Product
Agrupe os **alias** e deixe o **import** separado

2022-01-05 14:38 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/management.ex
> +  alias Myapp.Services.ElasticsearchService
Aqui também pode ser reescrito da seguinte forma

```
alias Myapp.Services.{RedisService, ElasticsearchService}
```

2022-01-05 14:38 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/plugs/get_product_plug.ex
>    defp find_by_id(conn, nil), do: assign(conn, :get_product, {:error, :bad_request})
Estou comentando nessa linha porque o github não deixou eu marcar a linha do método `get_product`. Mas o método `get_product` deveria ser privado. Mas melhor ainda seria remover ele e chamar direto o `find_by_id` no `call`

2022-01-05 14:38 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/plugs/get_product_plug.ex
>      else
Nesse caso, no lugar desse `with`, ficaria melhor um `if` ou um `with` parecido com isso:

```
with %Product{} = product <- Management.get_product(id) do
```

2022-01-05 14:38 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/plugs/get_product_plug.ex
>      else
`:get_product` esta mais para nome de função, nesse caso voce esta usando como valor, então ficaria melhor somente como `product` e remover a tupla com :ok e :erro e se não achar o produto, dar um halt() e retornar que o produto não foi encontrado, isso vai poupa-lo tambem de ter que sempre verificar no controller

2022-01-06 20:00 UTC, NoahCamargo requested changes

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/management.ex
> +  def list_products(), do: list_products([])
Os únicos casos que você usa essa função sem parâmetro é nos testes, então o que você pode fazer para resumir isso é na assinatura com parâmetro adicionar um default `def list_products(filters \\ [])` e remove esta

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/elasticsearch_service.ex
> +  @index Application.get_env(:myapp, Myapp.Elasticsearch)[:index]
Um cuidado a se tomar quando jogar valores que podem mudar em atributos de modulo é que um atributo é criado em tempo de compilação

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/elasticsearch_service.ex
> +    do: {:ok, Enum.map(hits_list, fn x -> x[:_source] end)}
Da para resumir essa lambda da seguinte forma `{:ok, Enum.map(hits_list, &(&1[:_source]))}`

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/plugs/get_product_plug.ex
> +    |> Plug.Conn.halt()
Como você já importou o `Conn`, poderia chamar o `halt()` direto

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +  def create(conn, _different_params), do: send_bad_request(conn)
Poderia ser um plug também, que verifica se o produto foi passado

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/management.ex
> +        RedisService.set(client, product_key, product)
Se o produto não existir, vai salvar vazio no cache? Talvez seja melhor não salvar

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp_web/controllers/product_controller.ex
> +  defp send_product(conn, product), do: render(conn, "show.json", product: product)
No lugar de ter que chamar essa função, poderia ser um matching com a estrutura do produto no fallback

2022-01-06 20:00 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/management.ex
> +      save_product_on_els(product)
Talvez seja bom adicionar as funções de mandar para o elastic ao with, com a intenção de caso ele retorne um erro, nem salve. Para evitar de ter produto faltando, desatualizado ou a mais no elastic e retornar no index

2022-01-10 19:03 UTC, NoahCamargo requested changes

2022-01-10 19:03 UTC, NoahCamargo commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert products = json_response(conn, 200)["products"]
Esse assert não tem um pattern para casar

2022-01-10 19:03 UTC, NoahCamargo commented on phoenix/app/myapp/test/myapp_web/controllers/product_controller_test.exs
> +      assert json_response(conn, 201)
O `json_response` não precisa de assert para lançar o erro

2022-01-11 14:04 UTC, merged