Desafio 5
bruno-br/onboarding_environment pull request #5
Opened 2022-01-19 14:10 UTC by bruno-br

2022-01-19 14:41 UTC, phrodrigues commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +    RedisService.set(redis_client, report_title, report)
O report tem que ser salvo em disco, e pode gerar problemas salvar o report num cache caso o arquivo seja muito grande

2022-01-19 14:41 UTC, phrodrigues commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +  defp generate_report(report_title, get_list_function) do
O nome desse método coincide com o do worker, mas a funcionalidade não é semelhante. Seria melhor um enqueue_report ao meu ver

2022-01-19 19:57 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +    Exq.enqueue(Exq, "report", GenerateReportWorker, [report_title, get_list_function])
Essa funçao pode validar o retorno de `enqueue` e retornar um erro para devolver ao cliente.

2022-01-19 19:58 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +    |> RedisService.get("#{report_title}_status")
Evita uso do operador pipe |> apenas uma vez

2022-01-19 20:03 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +  defp generate_report_data(report_title, list) do
`report_title` não é utilizado nessa função

2022-01-19 20:04 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +    list = apply(module_str, function_name_str, args)
da um espaço e mantém só `apply(module_str, function_name_str, args)` na última linha

2022-01-19 20:06 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +      [] ->
se `CsvFormatService.get_csv_string(list)` retornar "" tu não precisa desse match

2022-01-19 20:09 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +         :ok <- set_report_status(redis_client, report_title, :generating, expiration_in_seconds),
Dessa forma o report tem no máximo 60 segundos para ser gerado, e só fica disponível por 60 segundos.

2022-01-19 20:10 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/workers/generate_report_worker.ex
> +    do: RedisService.start() |> RedisService.del(get_report_status_key(report_title))
Evite single pipes

2022-01-19 20:15 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +        {:service_unavailable, "This report is still being generated"}
Aqui cabe melhor o erro 425

2022-01-19 20:21 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/services/products_reports_service_test.exs
> +    test "calls reports service with correct data" do
O que ocorre quando da erro?

2022-01-19 20:25 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/services/products_reports_service_test.exs
> +  describe "request_report/0" do
`request_report/2` *

2022-01-19 20:28 UTC, ArthurFreitas commented on phoenix/app/myapp/test/myapp/services/reports_service_test.exs
> +     get: fn _redis_client, key ->
Pode fazer pattern matching na própria declaração de função https://elixirschool.com/en/lessons/basics/functions/#pattern-matching

2022-01-21 15:44 UTC, NoahCamargo requested changes

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +         csv <- matrix_to_csv(matrix) do
Como matrix_to_csv, casa com qualquer coisa, joga direto dentro do "do"

```
{:ok, matrix_to_csv(matrix)}
```

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +    |> List.first()
Para não precisar dar  o first aqui, voce poderia pegar o header direto no match do get_matrix

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +    with {:ok, matrix} <- get_matrix(data),
Pelo que eu vi o get_matrix nunca vai retornar algo diferente de {:ok, matrix}, então nesse caso não precisaria do with nem retornar o :ok. Fazendo essa mudança, voce poderia transformar esse with em um pipeline, tambem

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +    end
Como seu with sempre retornara :ok, não precisaria desse else, nem do with

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +    do: RedisService.get(RedisService.start(), "#{report_title}_status")
Para não ter que ficar iniciando toda hora, talvez seja interessante usar um gemserver

2022-01-21 15:44 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +    with {:ok, :completed} <- get_report_status(report_title),
Eu só vou poder baixar meu report uma vez?

2022-01-21 16:33 UTC, bruno-br commented on phoenix/app/myapp/lib/myapp/services/reports_service.ex
> +    with {:ok, :completed} <- get_report_status(report_title),
Enquanto nao tiver expirado vai retornar sempre o mesmo, depois de expirar vai gerar um novo

2022-01-21 17:04 UTC, NoahCamargo requested changes

2022-01-21 17:04 UTC, NoahCamargo commented on phoenix/app/myapp/test/myapp/services/reports_service_test.exs
> +      expected_response = {:ok, @report_data}
Coloca um parenteses para melhorar a leitura do test_with_mock

```
  test_with_mock("returns report if it already exists", Exq,
    enqueue: fn _exq, _queue, _worker, _args -> {:ok, "job_id"} end
  ) do
  end
```

2022-01-24 19:02 UTC, ArthurFreitas commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +    rows = get_rows(maps_list)
Eu não rodei o projeto para verificar, mas aqui não deveria ser get_rows(tail), aparenta ta duplicando o header.

2022-01-24 19:53 UTC, bruno-br commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +    rows = get_rows(maps_list)
No get_headers ele pega so as keys do primeiro elemento pra colocar na primeira linha do csv. No get_rows ele pega os values de todos os elementos incluindo o primeiro

2022-01-26 14:47 UTC, NoahCamargo approved these changes

2022-01-26 14:47 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/csv_format_service.ex
> +      any -> {:error, any}
Esse any aparentemente não sera necessário, já que você definiu todos os retornos da função get_matrix

2022-01-26 16:47 UTC, ArthurFreitas approved these changes

2022-01-26 17:07 UTC, merged