Desafio 6
bruno-br/onboarding_environment pull request #6
Opened 2022-02-07 20:25 UTC by bruno-br

2022-02-08 13:03 UTC, NoahCamargo requested changes

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/myapp/lib/myapp/services/mailer_service.ex
> +  defp format_keys_and_values(%{} = map),
Utilize uma biblioteca para converter para JSON

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/myapp/test/myapp/services/reports_mailer_service_test.exs
> +      assert ReportsMailerService.send_email("report title", @attachment) == @success_response
Esse e o teste anterior poderiam estar juntos

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/mailerapp/test/mailerapp_web/controllers/send_email_controller_test.exs
> +    {:ok, conn: put_req_header(conn, "accept", "application/json")}
O retorno de setup pode ser tanto uma Keyword, tuple, ou tuple com :ok, nesse caso, passe direto a Keyword:

```
[conn: put_req_header(conn, "accept", "application/json")]
```

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/mailerapp/test/mailerapp_web/controllers/send_email_controller_test.exs
> +      response(conn, 202)
Nesse caso, voce poderia fazer um unico pipe:

```
conn
|> post(Routes.send_email_path(conn, :handle))
|> response(202)
```

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/mailerapp/test/mailerapp_web/controllers/send_email_controller_test.exs
> +      "returns 202 status code if SendEmailService.send is successful",
Como você já testa a action, recebendo os parâmetros corretamente, esse teste não seria necessário e você poderia mover o `response(conn, 202)`, para o teste "send correct params to SendEmailService.send".

Outro ponto importante é que o próprio teste serve como documentação para outros devs, então um dev ver que no teste se eu não enviar parâmetro ainda tenho uma resposta de sucesso, o mesmo pode entender que é assim o uso do enpoint, porem é necessário que os parâmetros sejam enviados

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/mailerapp/test/mailerapp/email_test.exs
> +      assert_called(Bamboo.Email.put_attachment(@valid_email, :_))
Não da para validar a estrutura criada?

2022-02-08 13:03 UTC, NoahCamargo commented on phoenix/app/mailerapp/lib/mailerapp_web/controllers/send_email_controller.ex
> +      {:error, reason} -> send_resp(conn, :internal_server_error, reason)
Poderia jogar esses send_resp para um fallback

2022-02-09 11:42 UTC, NoahCamargo requested changes
Crie um container separada para rodar o mailer, de forma a simular um ambiente de micro serviços onde cada um tem sua maquina

2022-02-10 12:46 UTC, NoahCamargo requested changes

2022-02-10 12:46 UTC, NoahCamargo commented on docker-compose.yml
> +      - 4444
No Dockerfile as portas estão ao contrario

2022-02-10 12:47 UTC, ArthurFreitas commented on mailerapp/mailerapp/test/mailerapp/email_test.exs
> +  @email_params %{
Pode colocar as constantes num setup_all

2022-02-10 12:47 UTC, ArthurFreitas commented on mailerapp/mailerapp/test/mailerapp/email_test.exs
> +      assert_called(Bamboo.Email.new_email(@email_params))
Esse assert poderia estar no teste de cima

2022-02-10 12:48 UTC, ArthurFreitas commented on mailerapp/mailerapp/test/mailerapp/email_test.exs
> +      bamboo_attachment = %Bamboo.Attachment{
Como é constante pode extrair para o setup_all

2022-02-10 12:50 UTC, ArthurFreitas commented on mailerapp/mailerapp/test/mailerapp/email_test.exs
> +      assert_not_called(Bamboo.Email.put_attachment(@valid_email, :_))
Esse assert pode estar no primeiro teste, agregando os asserts da mesma ação tu iria ter menos testes na suite o que a faria rodar mais rápido.

2022-02-10 19:05 UTC, merged